spring:
  profiles:
    active: prod
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  cors:
    allowed-origins: http://localhost:4200
  frontend-url: http://localhost:4200

shopify:
  access-token: ${SHOPIFY_ACCESS_TOKEN:}
  api-version: 2024-07
  oauth-client-id: ${SHOPIFY_CLIENT_ID}
  oauth-client-secret: ${SHOPIFY_CLIENT_SECRET}
  oauth-redirect-uri: "http://localhost:8080/api/shops/onboard/callback"
  oauth-scopes: "read_orders,read_customers"

security:
  jwt:
    secret: "change-me-to-a-very-long-secret-key-please-32-bytes-min"
    ttl-seconds: 86400
  encryption:
    key-base64: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
