spring:
  profiles:
    active: prod
  config:
    import: optional:file:.env[.properties]
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  cors:
    allowed-origins: http://localhost:4200
  frontend-url: http://localhost:4200

shopify:
  base-url: https://cssstudio-2.myshopify.com
  access-token:
  api-version: 2024-07
  oauth-client-id: 582d6ed717246fc35ea8064b491f51fd
  oauth-client-secret: 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
  oauth-redirect-uri: "http://localhost:8080/api/shops/onboard/callback"
  oauth-scopes: "read_orders,read_customers"

security:
  jwt:
    secret: "change-me-to-a-very-long-secret-key-please-32-bytes-min"
    ttl-seconds: 86400
  encryption:
    key-base64: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
